[build]
  command = "npm run build:netlify"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api-connectivity-test"
  to = "/api-test"
  status = 301
  force = true 